Translate "Initializers" section
cloud-native-lab/what-happens-when-k8s pull request #3
Opened 2019-02-06 13:11 UTC by shiftky

4章 Initializers の日本語訳を追加します。
特にレビューしていただきたいポイントはコメントのほうに記載します。

2019-02-06 13:14 UTC, shiftky commented on README-JP.md
> +オブジェクトがデータストアに永続化された後、オブジェクトは apiserver によって完全に可視化されることや、一連の [イニシャライザ (intializers)](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) が実行されるまでスケジュールされることはありません。イニシャライザ
この章にいくつかある "made visible" を "可視化される" と訳していますが、適切な訳が他にあれば教えてください!

2019-02-06 13:20 UTC, shiftky commented on README-JP.md
> +あなたの鋭い目は潜在的な問題を発見したかもしれません。リソースが kube-apiserver によって可視化されていない場合、どのようにしてユーザランドのコントローラはリソースを処理することができるのでしょうか？この問題を回避するために、 kube-apiserver は初期化されていないものを含む _全ての_ オブジェクトを返す `?includeUninitialized` クエリパラメー
"eagle-eyed" の訳をどうするか迷いました。今の訳の他に、 "鋭い観察眼" や、 "eyed" にこだわらず "鋭い洞察力" とするなど考えてみました。どうするのが適切でしょうか...!?

2019-02-07 06:09 UTC, makocchi-git commented on README-JP.md
> +あなたの鋭い目は潜在的な問題を発見したかもしれません。リソースが kube-apiserver によって可視化されていない場合、どのようにしてユーザランドのコントローラはリソースを処理することができるのでしょうか？この問題を回避するために、 kube-apiserver は初期化されていないものを含む _全ての_ オブジェクトを返す `?includeUninitialized` クエリパラメー
こんな感じはいかがでしょう。

鋭い観察眼を持つあなたは些細な潜在的な問題を見つけるかもしれません。

2019-02-07 06:09 UTC, makocchi-git commented on README-JP.md
> +オブジェクトがデータストアに永続化された後、オブジェクトは apiserver によって完全に可視化されることや、一連の [イニシャライザ (intializers)](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) が実行されるまでスケジュールされることはありません。イニシャライザ
`可視化` でも意味は通じると思うけども、apiserver 側からすると `公開` のほうが自然かな？

2019-02-07 06:16 UTC, shiftky commented on README-JP.md
> +オブジェクトがデータストアに永続化された後、オブジェクトは apiserver によって完全に可視化されることや、一連の [イニシャライザ (intializers)](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) が実行されるまでスケジュールされることはありません。イニシャライザ
確かに、そのほうが自然ですね...!  なおしてみます!

2019-02-12 06:18 UTC, chokkoyamada requested changes
一点コメントしました。 @shiftky

2019-02-12 06:18 UTC, chokkoyamada commented on README-JP.md
> +オブジェクトがデータストアに永続化された後、オブジェクトは apiserver によって完全に公開されることや、一連の [イニシャライザ (intializers)](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) が実行されるまでスケジュールされることはありません。イニシャライザは
`it is not made fully visible by the apiserver or scheduled`  / `until a series of intializers have run`
この2節に分けられると思うので、 

`一連のinitializerが実行完了するまで、apiserverによって完全に公開されたりスケジュールされることはありません`

とするのが正しい気がします

2019-02-12 09:33 UTC, shiftky commented on README-JP.md
> +オブジェクトがデータストアに永続化された後、オブジェクトは apiserver によって完全に公開されることや、一連の [イニシャライザ (intializers)](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) が実行されるまでスケジュールされることはありません。イニシャライザは
なるほど...!  直してみます!

2019-02-13 03:09 UTC, chokkoyamada approved these changes

2019-02-13 03:09 UTC, chokkoyamada commented
ありがとうございます。マージします

2019-02-13 03:09 UTC, merged