Add translation of kube-apiserver section
cloud-native-lab/what-happens-when-k8s pull request #4
Opened 2019-02-06 17:44 UTC by ww24

2章 kube-apiserver の日本語訳を追加します。

## Review points
- `Admission controller` をうまく訳せなかったのでカタカナ表記にしました
- 特に `we are who we say we are` と `we may be who we say we are` の適切な日本語訳が分かりませんでした。ご教示ください 🙏

2019-02-07 00:24 UTC, kentakozuka commented
```
we: 我々
who we say we are: （我々が）本人であると主張した人物
```
って感じでしょうか。

2019-02-07 06:12 UTC, makocchi-git commented on README-JP.md
> +kube-apiserverが認可を扱う方法は認証ととても似ています。flagの入力に基づいて、すべての受信リクエスト毎に認可方式を組み立てます。_すべての_ 認可方式がリクエストを拒否した場合、リクエストの結果として`Forbidden`が応答され、[それ以降は処理されません](https://github.com/kubernetes/apiserver/blob/e30df5e70ef91
ここの `flag` は `フラグ` にしておきましょうか

2019-02-07 08:48 UTC, ww24 commented on README-JP.md
> +kube-apiserverが認可を扱う方法は認証ととても似ています。flagの入力に基づいて、すべての受信リクエスト毎に認可方式を組み立てます。_すべての_ 認可方式がリクエストを拒否した場合、リクエストの結果として`Forbidden`が応答され、[それ以降は処理されません](https://github.com/kubernetes/apiserver/blob/e30df5e70ef91
🙆

2019-02-07 09:09 UTC, ww24 commented
修正反映しました。

2019-02-12 05:23 UTC, chokkoyamada commented on README-JP.md
> +_すべての_ 認証方式が失敗すると、[リクエストは失敗](https://github.com/kubernetes/apiserver/blob/20bfbdf738a0643fe77ffd527b88034dcde1b8e3/pkg/authentication/request/union/union.go#L71)して集約されたエラーが返却されます。認証が施工すると`Authorizati
>認証が施工すると
「認証が成功すると」のタイポですかね

2019-02-12 05:32 UTC, chokkoyamada commented on README-JP.md
> +kube-apiserverが認可を扱う方法は認証ととても似ています。フラグの入力に基づいて、すべての受信リクエスト毎に認可方式を組み立てます。_すべての_ 認可方式がリクエストを拒否した場合、リクエストの結果として`Forbidden`が応答され、[それ以降は処理されません](https://github.com/kubernetes/apiserver/blob/e30df5e70ef912
`If a single authorizer approves, the request proceeds.` の部分が訳出されてないように思いました。無くても支障はないですが、あったほうがいいかと思いました。

2019-02-12 05:49 UTC, chokkoyamada commented on README-JP.md
> +認証はユーザーが権限を持っているかどうかについて答える事に焦点を当てていますが、一方でアドミッションコントローラーはリクエストを傍受してクラスタのより広い期待値とルールにマッチするよう保証します。これらはオブジェクトがetcdで永続化される前の最後の砦です。そのため操作が予期せぬ結果や悪影響を生じないよう、残りのシステム確認をカプセル化します。
>認証はユーザーが権限を持っているかどうかについて答える事に焦点を当てていますが

ここは

>Whilst authorization is focused on answering whether a user has permission

に相当する訳文だと思うので、そうすると 「認証」ではなく「認可」が正しいと思います

2019-02-12 05:53 UTC, chokkoyamada commented on README-JP.md
> +認証はユーザーが権限を持っているかどうかについて答える事に焦点を当てていますが、一方でアドミッションコントローラーはリクエストを傍受してクラスタのより広い期待値とルールにマッチするよう保証します。これらはオブジェクトがetcdで永続化される前の最後の砦です。そのため操作が予期せぬ結果や悪影響を生じないよう、残りのシステム確認をカプセル化します。
[nits] 「カプセル化」という訳語はオブジェクト指向の文脈で、必要最低限の機能のみを外に公開しそれ以外は閉じるという印象を与えると思いました。ここでいう `encapsulate the remaining system checks` は、「その他のシステム関係のチェックを一手に引き受ける」というような訳だとより自然な気がしました。

2019-02-12 05:59 UTC, chokkoyamada commented on README-JP.md
> +- `ResourceQuota`はネームスペース内のオブジェクト(pods, rc, service load balancers)の数もしくは全体の消費リソース(cpu, memory, disk)を算出して拒否します。
[nits]
>全体の消費リソース

「消費リソースの総計」などと訳したほうが適切なように思いました。そのまま読むと、「ネームスペース内の」との対比で「全体の」と読めてしまう印象を受けました。

2019-02-12 06:00 UTC, chokkoyamada requested changes
@ww24 レビューしました。nitsは個人的な感想なので対応いただかなくても構いません。

2019-02-15 06:34 UTC, ww24 commented
お待たせしました :bow:
問題なければ merge お願いします。

2019-02-15 07:11 UTC, chokkoyamada approved these changes

2019-02-15 07:12 UTC, chokkoyamada commented
@ww24 ありがとうございます！マージします

2019-02-15 07:12 UTC, merged