Translate kubelet section
cloud-native-lab/what-happens-when-k8s pull request #6
Opened 2019-02-08 05:19 UTC by tani-yu

kubelet seectionの前半部分翻訳しました。

レビューお願いします 🙇

2019-02-12 05:40 UTC, shiftky commented on README-JP.md
> +1. Pod用のデータディレクトリが作成されます。Podディレクトリ（通常は/va/run/kubelet/pods/<pod ID>）、ボリュームディレクトリ (<podDir>/valumes)、pluginsディレクトリ（<podDir>/plugins）が含まれます。
typo 👀  (/va/run/)

path の文字列など、原文の方ではバッククオートで囲ってインラインコード化されているところがあるようなので、
表記を合わせておくのが良さそうです

2019-02-12 08:38 UTC, chokkoyamada commented on README-JP.md
> +現時点でセットアップのほとんどが終わり、コンテナを立ち上げる準備ができました。立ち上げるソフトウェアは、コンテナランタイムと呼ばれています（例えば、dockerやrkt）。拡張性を高めるために、kubeletのv1.5.0からCRI(Container Runtime Interface)と呼ばれる概念を使用しています。一言で言うと、CRIはkubeletと特定のランタイム実装の間の抽象化を提供
[nits] 原文と合わせるために`拡張性を高めるために`の前で段落変えたいです。(後でドキュメント全体を体裁整えるときに対応するので、今対応いただかなくて大丈夫です)

2019-02-12 08:41 UTC, chokkoyamada commented on README-JP.md
> +現時点でセットアップのほとんどが終わり、コンテナを立ち上げる準備ができました。立ち上げるソフトウェアは、コンテナランタイムと呼ばれています（例えば、dockerやrkt）。拡張性を高めるために、kubeletのv1.5.0からCRI(Container Runtime Interface)と呼ばれる概念を使用しています。一言で言うと、CRIはkubeletと特定のランタイム実装の間の抽象化を提供
`well-suited to performing Kubernetes operations` が `kubernetes操作でより良いパフォーマンスを出せるAPI` と訳されていますが、パフォーマンスが良いという意味はないと思うので、 `Kubernetesの操作に適した`くらいにしておくのがいいと思います

2019-02-12 08:43 UTC, chokkoyamada commented on README-JP.md
> +現時点でセットアップのほとんどが終わり、コンテナを立ち上げる準備ができました。立ち上げるソフトウェアは、コンテナランタイムと呼ばれています（例えば、dockerやrkt）。拡張性を高めるために、kubeletのv1.5.0からCRI(Container Runtime Interface)と呼ばれる概念を使用しています。一言で言うと、CRIはkubeletと特定のランタイム実装の間の抽象化を提供
>cre Kubernetesのcode変更する必要がないので

タイポが含まれてますかね。

`Kubernetesのコアのコードを変更する必要がないので` とかでしょうか

2019-02-12 08:48 UTC, chokkoyamada commented on README-JP.md
> +ここで、コンテナのデプロイの話に戻りましょう… 最初にpodが開始されたとき、kubeletは[ `RunPodSandbox`リモートプロシジャーコール（RPC）を呼び出します](https://github.com/kubernetes/kubernetes/blob/2d64ce5e8e45e26b02492d2b6c85e5ebfb1e4761/pkg/kubelet/kuberunti
`A "sandbox" is a CRI term to describe a set of containers` / `which in Kubernetes parlance is` / `you guessed it` / `a Pod`. 

`sandboxはコンテナの人まとまりを表せすCRIの用語で、Kubernetes用語でいうと、ご想像のとおり、podです`
というような訳になるかと。「sandboxはCRI用語である」が肝の部分で、「sandboxはkubernetesの用語である」と読めてしまうように思うので、訳の修正が必要と思います

2019-02-12 09:02 UTC, chokkoyamada commented on README-JP.md
> +Cgroupsは、LInuxがリソースを割り与える方法であるため（リソース使用量を監視する警察のような）重要になります。Dockerはホストプロセスに支配されたリソースと強制されたisolationのkernel機能を使います。詳細はb0rk'sの驚くべき投稿を確認して下さい。 [What even is a Container?](https://jvns.ca/blog/2016/10/10
[nits]
>LInux

Linux のタイポ

2019-02-12 09:03 UTC, chokkoyamada commented on README-JP.md
> +Cgroupsは、LInuxがリソースを割り与える方法であるため（リソース使用量を監視する警察のような）重要になります。Dockerはホストプロセスに支配されたリソースと強制されたisolationのkernel機能を使います。詳細はb0rk'sの驚くべき投稿を確認して下さい。 [What even is a Container?](https://jvns.ca/blog/2016/10/10
[nits]
>b0rk's

`'s`は不要

2019-02-12 09:10 UTC, chokkoyamada commented on README-JP.md
> +Cgroupsは、LInuxがリソースを割り与える方法であるため（リソース使用量を監視する警察のような）重要になります。Dockerはホストプロセスに支配されたリソースと強制されたisolationのkernel機能を使います。詳細はb0rk'sの驚くべき投稿を確認して下さい。 [What even is a Container?](https://jvns.ca/blog/2016/10/10
[imo]
>Dockerはホストプロセスに支配されたリソースと強制されたisolationのkernel機能を使います。

これが訳として読んでいてよくわかりませんでした。

>Docker uses both of these Kernel features to host a process that has guaranteed resources and enforced isolation. 

この部分だと思うので、

`Dockerはこれら両方のKernelの機能を使い、リソースが確保され隔離が強制されたプロセス（つまりコンテナ）をホストします`

とかでしょうか。

2019-02-12 09:15 UTC, chokkoyamada requested changes
@tani-yu 個人的意見も多く含まれていますが、レビューしました 🙇 
このセクション他と比べても訳が難しいです...

2019-02-12 09:58 UTC, shiftky commented on README-JP.md
> +kubeletはkubernetesクラスターすべてのノードで動いるエージェントで、Podのライフルサイクルの責任を負っています。これは、Pod（kubernetesの概念）の抽象化と構成要素であるコンテナの間のすべての変換ロジックを取り扱うことを意味します。また、ボリュームのマウント、コンテナのlogging、ガベージコレクションとその他の重要なことに関連するのも取り扱っています。
> その他の重要なことに関連するのも取り扱っています。

typo っぽいところがあるのと、いくつかの単語に対応する訳が抜けていそうです。
`その他の多くの重要なことに関連するすべてのロジックを取り扱っています。` といった感じでしょうか。

2019-02-12 09:58 UTC, shiftky commented on README-JP.md
> +pauseコンテナの２つ目の役割はPID ネームスペースを関連付けることです。これらのnamespaceのタイプは木の階層構造を形成し、 トップの"init"プロセスが死んだプロセスの ”刈り取り” をする責任を持つ。どのように動くかの詳細は、[great blog post](https://www.ianlewis.org/en/almighty-pause-container)をチェックし
> ”刈り取り” をする責任を持つ。

ですます調で

2019-02-13 08:35 UTC, tani-yu commented
@chokkoyamada 指摘していただいた部分修正しました。ご確認お願いします

2019-02-14 10:54 UTC, chokkoyamada approved these changes

2019-02-14 10:55 UTC, chokkoyamada commented
@tani-yu 対応ありがとうございます！

2019-02-14 10:55 UTC, merged