Tranlate 'control loops' section
cloud-native-lab/what-happens-when-k8s pull request #7
Opened 2019-02-08 12:13 UTC by zuiurs

Control loops セクションの日本語訳を追加します。

2019-02-08 12:23 UTC, zuiurs reviewed
ここの Burst Count というのは ReplicaSetSpec の replicas フィールドのことを指しているという認識であっているのでしょうか？

2019-02-08 12:29 UTC, zuiurs commented on README-JP.md
> +その気になるイベントとは「作成」です。Deployment コントローラーにより ReplicaSet が作成されたとき、その ReplicaSet コントローラーは新規の ReplicaSet の [状態を調べ](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.
ここの Burst Count というのは ReplicaSetSpec の replicas フィールドのことを指しているという認識であっているのでしょうか？

2019-02-08 12:29 UTC, zuiurs commented on README-JP.md
> +1. スケジューラーが起動すると [デフォルトの Predicate チェインが登録](https://github.com/kubernetes/kubernetes/blob/2d64ce5e8e45e26b02492d2b6c85e5ebfb1e4761/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L65-L81)
Predicate の部分何かいい訳ありますでしょうか？
各 Node に対して対象の Pod が動くのに適してるか判断する機能、なので Predicate Function ということだと思うのですが日本語化しづらく。。。

2019-02-12 07:38 UTC, chokkoyamada requested changes
@zuiurs リンクURLの修正だけお願いします

2019-02-12 07:38 UTC, chokkoyamada commented on README-JP.md
> +その気になるイベントとは「作成」です。Deployment コントローラーにより ReplicaSet が作成されたとき、その ReplicaSet コントローラーは新規の ReplicaSet の [状態を調べ](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.
それで合っていると思います。

@makocchi-git どうでしょ

2019-02-12 07:38 UTC, chokkoyamada commented on README-JP.md
> +インフォーマーがコントローラーに関してどのように機能するかについての詳細は、この [ブログ](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L460) をチェックしてください。
リンク先のURLが間違ってます。
http://borismattijssen.github.io/articles/kubernetes-informers-controllers-reflectors-stores
こちらが正しいリンク

2019-02-12 07:38 UTC, chokkoyamada commented on README-JP.md
> +スケジューラーはコントロールプレーンのコンポーネントとして単独で動作し、他のコントローラー同様にイベントの監視と状態調整の試行といった操作を行います。今回の場合は PodSpec の `NodeName` が空になっている [Pod をフィルタ](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/f
>https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go

このリンクが404ですが、元の英文も404ですね... とりあえず事実の指摘まで

2019-02-12 07:38 UTC, chokkoyamada commented on README-JP.md
> +1. スケジューラーが起動すると [デフォルトの Predicate チェインが登録](https://github.com/kubernetes/kubernetes/blob/2d64ce5e8e45e26b02492d2b6c85e5ebfb1e4761/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L65-L81)
引数をとってbooleanを返却するインタフェースのことを指すので、`真偽判定をする関数`とかですかね...

`Predicate`のままでも、わかる人にはわかると思います...

2019-02-12 07:58 UTC, makocchi-git commented on README-JP.md
> +その気になるイベントとは「作成」です。Deployment コントローラーにより ReplicaSet が作成されたとき、その ReplicaSet コントローラーは新規の ReplicaSet の [状態を調べ](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.
burstCount はひょっとしたら[これ](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L66)のことを指しているのかなぁと思ったり
```
BurstReplicas = 500
```

新規で deployment が作成された時は pod は 0 だと思いますが、その後に 500 pod 以内であれば一気に作成されるっていうことになりますかね。
っていう意味で burst count って言っているのかもしれませんね。

2019-02-12 11:59 UTC, zuiurs commented on README-JP.md
> +その気になるイベントとは「作成」です。Deployment コントローラーにより ReplicaSet が作成されたとき、その ReplicaSet コントローラーは新規の ReplicaSet の [状態を調べ](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.
ありがとうございます🙇‍♂️
どっちなんでしょう... Deployment から受け継ぐっていうのと、その数を守って作る、となると replicas のような気もするんですよね。とはいえ `BurstReplicas` も何か関係しているような気もしています。。
一旦バーストカウントで置いておきます。

2019-02-12 12:06 UTC, zuiurs commented on README-JP.md
> +1. スケジューラーが起動すると [デフォルトの Predicate チェインが登録](https://github.com/kubernetes/kubernetes/blob/2d64ce5e8e45e26b02492d2b6c85e5ebfb1e4761/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L65-L81)
ありがとうございます。
Predicate の方がニュアンスが伝わりやすいのと、Predicate の説明が直後にあるので Predicate のままにしておこうと思います。

2019-02-12 12:08 UTC, zuiurs commented on README-JP.md
> +スケジューラーはコントロールプレーンのコンポーネントとして単独で動作し、他のコントローラー同様にイベントの監視と状態調整の試行といった操作を行います。今回の場合は PodSpec の `NodeName` が空になっている [Pod をフィルタ](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/f
ほんとですね。。。
他のリンクも地味に行がずれていたりするので、ひとまず元文に合わせます🙇‍♂️
ありがとうございます。

2019-02-13 03:09 UTC, chokkoyamada approved these changes

2019-02-13 03:10 UTC, merged