Translating kubelet parts
cloud-native-lab/what-happens-when-k8s pull request #9
Opened 2019-02-14 05:08 UTC by yasuhiro1711

よろしくお願いします。

2019-02-14 11:08 UTC, chokkoyamada commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceをホストする一時停止中のコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
`pause container`のpauseを一時停止中と訳してしまうと違うみたいです。 前項にもあるように、 pause container という役割のcontainerがあって、ここでいうpauseというのはシステムコールのpauseを呼び出すから？というのが由来のようです。
@makocchi-git 解説求む

2019-02-14 11:10 UTC, chokkoyamada commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceをホストする一時停止中のコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
前項に合わせて `pauseコンテナ`というようにしておきましょうか

2019-02-14 11:18 UTC, chokkoyamada commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceをホストする一時停止中のコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
https://www.ianlewis.org/en/almighty-pause-container
このあたり読んでいると、実際に一時停止をし続けてるコンテナなので「一時停止中のコンテナ」でも直訳としては問題ないが、この文脈ではそれ以上の役割をしているという感じですね

2019-02-14 11:23 UTC, chokkoyamada commented on README-JP.md
> +kubeletがPodのネットワークを設定すると、タスクを"CNI"プラグインに委任します。CNIは「Container Network Interface」の略で、Container Runtime Interfaceと同じように動作します。端的に言うと、CNIは、さまざまなネットワークプロバイダがさまざまなネットワーク実装をコンテナに使用できるようにするための抽象概念です。プラグインは登録さ
>kubelet interacts with them
`CNIとやりとりします`となってますが、kubeletがやりとりするのはPluginではないでしょうか？ CNIを仲介するインタフェースとして、kubeletとPluginが連携する、ということだと思いました。

2019-02-14 11:38 UTC, chokkoyamada commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceをホストする一時停止中のコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
参考　https://qiita.com/tkusumi/items/c2a92cd52bfdb9edd613#pause%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A

2019-02-14 11:57 UTC, chokkoyamada requested changes
@yasuhiro1711 レビューしました。ご確認お願いします。どちらにせよ明日にはいったんマージしたいと思います。

2019-02-14 14:53 UTC, yasuhiro1711 commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceをホストする一時停止中のコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
ありがとうございます！その通りかと思いました。参考リンクも拝見して納得です。

2019-02-14 14:54 UTC, yasuhiro1711 commented on README-JP.md
> +kubeletがPodのネットワークを設定すると、タスクを"CNI"プラグインに委任します。CNIは「Container Network Interface」の略で、Container Runtime Interfaceと同じように動作します。端的に言うと、CNIは、さまざまなネットワークプロバイダがさまざまなネットワーク実装をコンテナに使用できるようにするための抽象概念です。プラグインは登録さ
これはご指摘のとおりですね！

2019-02-14 14:54 UTC, yasuhiro1711 commented
指摘いただいたものを修正しました。よろしくお願いします。

2019-02-15 02:01 UTC, chokkoyamada approved these changes

2019-02-15 02:02 UTC, chokkoyamada commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceの情報を持つPuuseコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
x`puuse` 
○ `pause`

マージ後調整しますね！

2019-02-15 02:02 UTC, chokkoyamada approved these changes

2019-02-15 02:02 UTC, yasuhiro1711 commented on README-JP.md
> +さて、Podの土台が出来上がりました。　Pod間通信を可能にする全Namespaceの情報を持つPuuseコンテナです。　しかし、ネットワークはどのように機能しどのように設定されているのでしょうか？
失礼しました！お願いします！

2019-02-15 02:02 UTC, chokkoyamada commented
ありがとうございます！LGTM

2019-02-15 02:02 UTC, merged